export * from './formActions'

export const CONSTANTS={
    SUBMIT_CONTACT_FORM: "SUBMIT_CONTACT-FORM",
    ONCHANGE_FULLNAME: "ONCHANGE_FULLNAME",
    ONCHANGE_EMAIL: "ONCHANGE_EMAIL", 
    ONCHANGE_MESSAGE: "ONCHANGE_MESSAGE" 
}